### PR TITLE
Feature/flexible release

### PR DESCRIPTION
**Pull request by phillipjf**
This PR adds functionality to support:
- Custom OS Arch and Platform options as input to the action for matching release artifacts
- More flexible artifact naming and matching based on OS Arch and Platform

### CODE REVIEW

**Comment by phillipjf** [comment]
Hi @jaxxstorm please let me know if this is something to consider merging or any feedback is welcome. I reviewed the `CONTRIBUTING.md` guide but it does not seem applicable for this repository.

**Comment by jaxxstorm** [comment]
@phillipjf this looks awesome, thanks so much! I'll discuss with the team using it at Pulumi, this looks to be a breaking change to want to make sure we release appropriately.

**Comment by jaxxstorm** [comment]
@phillipjf would you mind adding some tests/integration tests for your changes?

**Comment by phillipjf** [comment]
@jaxxstorm thanks for the reply. I'll take a look at getting some tests added. Is there a preference for framework/etc. within the org? There aren't any existing tests to base off of. 

I also tried to make this change pretty backwards-compatible, so if you see anything breaking, I'm willing to update to accommodate.

**Comment by jaxxstorm** [comment]
sorry I think I was unclear, all I need is an example download in here: https://github.com/jaxxstorm/action-install-gh-release/blob/master/.github/workflows/test.yml

You've already got some examples in the readme, just add those to the workflow :)

**Comment by phillipjf** [comment]
@jaxxstorm thanks for the clarification. I pushed up an additional suite of jobs to test the changes I made. Looks like it  needs approval to run.

edit: actually -- glossed over using the `which` command with windows... I wanted to test pulling multiple `arch` combinations but I don't think it will be feasible without custom runners as all the hosted runners will be `amd64`

**Comment by phillipjf** [comment]
@jaxxstorm I revised the test action. I'll review the results once it's approved to run. You can cancel the previous run.

**Comment by phillipjf** [comment]
pushed a fix for the action..typo in the `platform` input.

**Comment by phillipjf** [comment]
I added `info` logging to aid in identifying situations where the user might need to identify what the action is searching. This gives the actual value reported by the runner along with what value is being used for searching (i.e. if it's being overridden by the arguments).

```
==> System reported platform: win32
==> Using platform: windows
==> System reported arch: x64
==> Using arch: amd64
searching for tfsec-checkgen-darwin-amd64 with (windows|amd64).*(windows|amd64).*.(tar.gz|zip)
...
```

Based on the last run, everything looks as expected.

**Comment by jaxxstorm** [comment]
Awesome! thanks for the amazing contribution

**Comment by phillipjf** [comment]
@jaxxstorm when you have a chance, can you create a tag/release for this?

**Pull request merged**
