### PR TITLE
adds .tgz to the list

### PR DESCRIPTION
**Pull request by damirka**
Working with the https://github.com/mystenlabs/sui repository, and it has binaries in `.tgz` format. Struggled to debug until realised that the archive extension is not recognised. 

Hopefully, this fixes the issue.

### CODE REVIEW

**Comment by damirka** [comment]
Huge fan of your action @jaxxstorm! Please, let me know which steps I should take in order to get this buddy in (if you're okay with it).

**Comment by jaxxstorm** [comment]
@damirka can you add a test for this repo to the tests? Once it's verified to work I'll merge

**Comment by damirka** [comment]
@jaxxstorm done! The test passes!

https://github.com/damirka/action-install-gh-release/actions/runs/9127063984/job/25096582513

**Comment by jaxxstorm** [comment]
Failing test is unrelated, so merging

**Pull request merged**
