### PR TITLE
Add binaries-location option

### LINKED ISSUE #25: Support binaries not at the top level for adding to PATH
If a github release has the binary under a bin folder it won't be easily accessible. It won't be found using the existing PATH add of just the top level folder.

It would be nice if the action included an option to specify an additional folder to add or perhaps add an output for the full path to the extracted folder.

### PR DESCRIPTION
**Pull request by jonaprieto**
This PR adds a new parameter to specify a relative path to the release archive where one can find the binaries. For example, if the binaries are located in the 'bin' directory of the release archive, the parameter should be `bin`. As multiple files may exist in the release archive, the option `rename-to` has no effect combined with `binaries-location.`

- Closes #25

### CODE REVIEW

**Comment by jaxxstorm** [comment]
@jonaprieto please readd the `node_modules` directory. GitHub actions requires that to function correctly.

**Comment by jonaprieto** [comment]
Ok, I didn't know.

**Comment by jonaprieto** [comment]
The README examples are used as the latest version, v0.10.0

**Comment by jaxxstorm** [comment]
Looks like there's still a big delta here between the original branch and your changes. Would be great to reduce that so i can adequately review it

**Comment by jonaprieto** [comment]
Ok, let me know if I need to do something else. After considering this PR, you need to generate the node_modules folder with the new updates again.

**Comment by jaxxstorm** [comment]
Thank you! can you add a smoke test to https://github.com/jaxxstorm/action-install-gh-release/blob/master/.github/workflows/test.yml?

**Pull request merged**
